---
kind: Service
apiVersion: v1
metadata:
  name: srv-jenkins-frontend
  labels:
    name: jenkins
    role: frontend
    env: devenv
spec:
  ports:
  - name: ui
    port: 8080
    targetPort: jenkins-m-http
    protocol: TCP
  - name: discovery
    port: 50000
    targetPort: jenkins-m-disco
    protocol: TCP
  - name: ws
    port: 8888
    targetPort: jenkins-m-ws
    targetPort: jenkins-m-ws
    protocol: TCP
  createExternalLoadBalancer: false
  selector:
    name: jenkins
    role: master
