---
kind: Service
apiVersion: v1
metadata:
  name: srv-jenkins-proxy
  labels:
    name: nginx
    role: jenkins-proxy
    env: devenv
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: jen-proxy-https
    protocol: TCP
  - name: http
    port: 80
    targetPort: jen-proxy-http
    protocol: TCP
  - name: ws
    port: 8888
    targetPort: jen-proxy-ws
    protocol: TCP
  selector:
    name: nginx
    role: jenkins-proxy
